CREATE DATABASE yeticave
  DEFAULT CHARACTER SET utf8
  DEFAULT COLLATE utf8_general_ci;
USE yeticave;

CREATE TABLE categories (
  id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  category VARCHAR(100) NOT NULL UNIQUE,
  class_category VARCHAR(100) UNIQUE
);

CREATE TABLE users (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name_user VARCHAR(100) NOT NULL,
  password_user VARCHAR(255) NOT NULL,
  email_user VARCHAR(255) NOT NULL UNIQUE,
  registration_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  avatar_user VARCHAR(64),
  contacts_user VARCHAR(255) NOT NULL
);

CREATE TABLE lots (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  description TEXT NOT NULL,
  img_lot VARCHAR(64) NOT NULL,
  start_price INT UNSIGNED NOT NULL,
  date_start DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  date_end DATE NOT NULL,
  bet_step INT UNSIGNED NOT NULL,
  category_id SMALLINT UNSIGNED NOT NULL,
  user_id INT UNSIGNED NOT NULL,
  winner_id INT UNSIGNED,
  FULLTEXT INDEX lot_search (title,description)
);

CREATE TABLE bets (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  date_bet DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  bet_amount INT NOT NULL,
  user_id INT UNSIGNED NOT NULL,
  lot_id INT UNSIGNED NOT NULL
);
